### ISSUE TITLE
 cannot import name 'joblib' from 'sklearn.externals' 

### ISSUE THREAD

**Issue by Tejindersingh1** [gmiaslab/ClassificaIO#3]
Line 128 in ClassificaIO.py 
ImportError: cannot import name 'joblib' from 'sklearn.externals'

**Comment by gmiaslab** [comment]
ClassificaIO is no longer under active development. The last stable version was developed under Python 3.6. The joblib module would have to be called directly in the code, i.e. "import joblib" - the current version will not work with newer versions of Python.
