### ISSUE TITLE
Gradio auth is broken on latest version

### ISSUE THREAD

**Issue by Talos0248** [gmiaslab/ClassificaIO#4]
When using version 2.0.2 of gradio, the auth function does not work. When I run:
iface2.launch(auth=("admin","password"))

I get the Traceback:
jinja2.exceptions.TemplateNotFound: login.html

I installed 1.7.7 and the code works just fine. Is there a template missing in the 2.0.2 version?

**Comment by gmiaslab** [comment]
ClassificaIO is no longer under active development. Please note that the above software is not used in ClassificaIO.
